//! Example: Query synthetic weather data using SQL
//!
//! This example demonstrates querying the synthetic weather dataset
//! generated by `scripts/data_gen.py`. The data contains random
//! temperature and humidity values for a 10x10 lat/lon grid over 7 days.
//!
//! Run with tracing enabled:
//!   RUST_LOG=info cargo run --example query_synthetic
//!   RUST_LOG=debug cargo run --example query_synthetic

mod common;

use std::sync::Arc;
use zarr_datafusion::datasource::zarr::ZarrTable;
use zarr_datafusion::reader::schema_inference::infer_schema_with_meta;

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    common::init_tracing();
    let ctx = common::create_local_context();

    // Load synthetic weather data (Zarr v3) with metadata for statistics
    let store_path = "data/synthetic_v3.zarr";
    let (schema, metadata) = infer_schema_with_meta(store_path).expect("Failed to infer schema");
    let schema = Arc::new(schema);

    println!("Synthetic Weather Data Schema:");
    for field in schema.fields() {
        println!("  {}: {:?}", field.name(), field.data_type());
    }
    println!("Total rows: {}", metadata.total_rows);

    let table = Arc::new(ZarrTable::with_metadata(schema, store_path, metadata));
    ctx.register_table("synthetic", table)?;

    common::run_query(
        &ctx,
        "Sample data (first 10 rows):",
        "SELECT * FROM synthetic LIMIT 10",
    )
    .await?;

    common::run_query(
        &ctx,
        "Filtered data (temperature > 5):",
        "SELECT time, lat, lon, temperature FROM synthetic WHERE temperature > 5 LIMIT 10",
    )
    .await?;

    common::run_query(
        &ctx,
        "Average temperature per day:",
        "SELECT time, AVG(temperature) as avg_temp FROM synthetic GROUP BY time ORDER BY time",
    )
    .await?;

    common::run_query(
        &ctx,
        "Total rows (optimized - uses statistics, no data scan):",
        "SELECT COUNT(temperature) as total FROM synthetic",
    )
    .await?;

    common::run_query(
        &ctx,
        "Coordinate bounds (optimized - uses statistics, no data scan):",
        "SELECT MIN(lat) as lat_min, MAX(lat) as lat_max, MIN(lon) as lon_min, MAX(lon) as lon_max FROM synthetic",
    )
    .await?;

    Ok(())
}
